definitions:
  triggering:
    push: &events
      events:
        - push
        - pull_request

workflows:
  musadorakit:
    name: MusadoraKit Workflow
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_SCHEME: "MusadoraKit"
        DESTINATIONS: "("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")"
        APP_ID: "Musadora"
    when:
      changeset:
        includes:
          - 'Sources'
          - 'Tests'
    triggering:
      <<: *events
    scripts:
      - name: Build Framework
        script: |
          #!/bin/zsh

          #declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              xcodebuild clean build \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation
          done
      - name: Test Framework
        script: |
          #!/bin/zsh
          
          #declare -a DESTINATIONS=("platform=iOS Simulator,name=iPhone 14" "platform=watchOS Simulator,name=Apple Watch Series 8 (45mm)" "platform=tvOS Simulator,name=Apple TV 4K (3rd generation)" "platform=macOS")
          for DESTINATION in "${DESTINATIONS[@]}"
            do
              set -o pipefail
              xcodebuild clean test \
                -scheme "$XCODE_SCHEME" \
                -destination "$DESTINATION" \
                -skipPackagePluginValidation | xcpretty --report junit
          done
        test_report: build/reports/junit.xml
    
  musadorakit-update-docs:
    name: MusadoraKit Docs Update Workflow
    environment:
      groups:
        - GitHub
    scripts:
      - name: Update DocC Documentation
        script: |
          sh build_docs.sh
          git add .
          git commit -m "[skip ci] Update DocC Documentation"
          git remote set-url origin https://rudrankriyam:$token@github.com/rryam/MusadoraKit.git
          git pull --ff-only
          git push origin main

  musadora: 
    name: Musadora TestFlight Workflow
    working_directory: Musadora
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.rudrankriyam.musadora
      vars:
        XCODE_PROJECT: "Musadora.xcodeproj"
        XCODE_SCHEME: "Musadora"
        APP_ID: "1578765152"
    integrations:
      app_store_connect: Rudrank ASC API Key
    triggering:
      <<: *events
    when:
      changeset:
        excludes: 
          - '**/*.md'
    
    scripts:
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_ID")
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags "-destination 'generic/platform=iOS' -skipPackagePluginValidation"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - rudrankriyam@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Testers
        submit_to_app_store: false
